FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.15 AS builder
WORKDIR /go/src/github.com/openshift/debug-network
COPY . .
ENV GO_PACKAGE github.com/openshift/debug-network

FROM registry.svc.ci.openshift.org/ocp/4.6:cli
COPY --from=builder /go/src/github.com/openshift/debug-network/debug-scripts/* /usr/bin/
RUN yum -y install git go jq tcpdump traceroute net-tools nmap-ncat pciutils strace numactl make; yum clean all
