FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
WORKDIR /go/src/github.com/openshift/network-tools
COPY . .
ENV GO_PACKAGE github.com/openshift/network-tools

FROM registry.svc.ci.openshift.org/ocp/4.7:base
COPY --from=builder /go/src/github.com/openshift/network-tools/debug-scripts/ /usr/bin/debug-network-scripts/
RUN yum -y install git go jq tcpdump nginx traceroute wireshark net-tools nmap-ncat pciutils strace numactl make; yum clean all
