#!/bin/bash
set -euo pipefail

source ./utils

description() {
  echo "Collect OVN networking metrics: master, node, and ovn"
}

help () {
  echo "This script collects OVN networking metrics: master, node, and ovn.
If output folder is not specified, local path will be used.

Usage: $USAGE [output_folder]

Examples:
  $USAGE
  $USAGE /some/path/metrics

  oc adm must-gather --image=$NETWORK_TOOLS_IMAGE -- $USAGE /must-gather
"
}

main() {
  dir=$(ensure_output_dir "${1:-}")
  echo "Output directory ${dir}"
  leader_host="$(get_ovnk_leader_node)"
  master_leader_pod="$(get_ovnk_leader_pod)"
  oc -n "$OVN_NAMESPACE" exec "$master_leader_pod" -c ovnkube-master -- curl "127.0.0.1:29102/metrics" > "$dir/$master_leader_pod-29102(master)"
  node_pod="$(oc get pods -n $OVN_NAMESPACE --field-selector spec.nodeName=$leader_host -l app=ovnkube-node -o=jsonpath='{.items..metadata.name}')"
  oc -n "$OVN_NAMESPACE" exec "$node_pod" -c ovnkube-node -- curl "127.0.0.1:29103/metrics" > "$dir/$node_pod-29103(node)"
  oc -n "$OVN_NAMESPACE" exec "$node_pod" -c ovnkube-node -- curl "127.0.0.1:29105/metrics" > "$dir/$node_pod-29105(ovn)"
}

case "${1:-}" in
  description) description ;;
  -h|--help) help ;;
  *) main "$@" ;;
esac